executor: KubernetesExecutor

fernetKey: "z18LcO61ndDxxw6doJFpKbU/00xu9xd+rmH5Jo0u66A="
webserverSecretKey: "uMfJGfu+wyyfw0NRz1x1rOeldetb+oRKr9lJxuZB+XI="

airflow:
  requirements:
    enabled: true
    path: /opt/airflow/dags/requirements.txt
  extraPipPackages:
    - astronomer-cosmos==1.11.0
    - dbt-core==1.8.8
    - dbt-postgres==1.8.2
    - aenum
    - deprecation
    - msgpack
    - pydantic
  config:
    core:
      base_log_folder: /opt/airflow/local_logs
      remote_logging: "False"
      dag_dir_list_interval: 10
    kubernetes:
      worker_pods_log_fetch_method: "ip"
      use_local_logs: true
      delete_worker_pods: true
      worker_pods_creation_batch_size: 1
      worker_pods_pending_timeout: 300
      logs_volume_subpath: ""

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/OrestOhorodnyk/dbt_repo_aggregator.git"
    branch: "cosmos"
    subPath: "."
    rev: "HEAD"
    depth: 1
    wait: 10
    maxFailures: 0

connections:
  - conn_id: postgres_dbt
    conn_type: postgres
    conn_host: postgres-service
    conn_login: dbt
    conn_password: dbt
    conn_schema: analytics
    conn_port: 5432

  - conn_id: kubernetes_default
    conn_type: kubernetes
    conn_extra: '{"in_cluster": true, "namespace": "airflow"}'

# ───────────── DAG + LOG host mounts ─────────────
web:
  env:
    - name: _PIP_ADDITIONAL_REQUIREMENTS
      value: "astronomer-cosmos==1.11.0 dbt-core==1.8.8 dbt-postgres==1.8.2 aenum deprecation msgpack pydantic"
  extraVolumes:
    - name: local-logs
      hostPath:
        path: /Users/o.ohorodnyk/airflow-dags/airflow_logs
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: local-logs
      mountPath: /opt/airflow/local_logs

scheduler:
  env:
    - name: _PIP_ADDITIONAL_REQUIREMENTS
      value: "astronomer-cosmos==1.11.0 dbt-core==1.8.8 dbt-postgres==1.8.2 aenum deprecation msgpack pydantic"
  extraVolumes:
    - name: local-logs
      hostPath:
        path: /Users/o.ohorodnyk/airflow-dags/airflow_logs
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: local-logs
      mountPath: /opt/airflow/local_logs

dagProcessor:
  env:
    - name: _PIP_ADDITIONAL_REQUIREMENTS
      value: "astronomer-cosmos==1.11.0 dbt-core==1.8.8 dbt-postgres==1.8.2 aenum deprecation msgpack pydantic"
  extraVolumes:
    - name: local-logs
      hostPath:
        path: /Users/o.ohorodnyk/airflow-dags/airflow_logs
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: local-logs
      mountPath: /opt/airflow/local_logs

triggerer:
  extraVolumes:
    - name: local-logs
      hostPath:
        path: /Users/o.ohorodnyk/airflow-dags/airflow_logs
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: local-logs
      mountPath: /opt/airflow/local_logs

workers:
  extraVolumes:
    - name: local-logs
      hostPath:
        path: /Users/o.ohorodnyk/airflow-dags/airflow_logs
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: local-logs
      mountPath: /opt/airflow/local_logs

# PostgreSQL
postgresql:
  image:
    repository: bitnami/postgresql
    tag: "latest"
  persistence:
    enabled: true
    size: 5Gi
  volumePermissions:
    enabled: false

# Disable internal PVC for logs (we use hostPath instead)
logs:
  persistence:
    enabled: false
